FROM python:3.7-slim

RUN apt-get -y update && \
    apt-get -y install apt-utils gcc python3-dev libev-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install locust

COPY ./locust_targets/ ./locust_targets/
WORKDIR locust_targets