FROM python:3.7-slim

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_proxy.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install gcc && \
    pip install -r requirements_proxy.txt

COPY ./api_composition_proxy/ /${PROJECT_DIR}/api_composition_proxy/
COPY ./configurations/ /${PROJECT_DIR}/configurations/
ENV RUN_FILE run_proxy.sh
COPY ./scripts/${RUN_FILE} /${PROJECT_DIR}/${RUN_FILE}
RUN chmod +x ${RUN_FILE}

CMD ./run_proxy.sh

