FROM tensorflow/tensorflow:latest as builder

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_test.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install gcc curl libev-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install -r requirements_test.txt

COPY ./src/app/ml/ /${PROJECT_DIR}/src/app/ml/
COPY ./src/app/constants.py /${PROJECT_DIR}/src/app/constants.py
COPY ./src/configurations/ /${PROJECT_DIR}/src/configurations/
COPY ./scripts/run_extract_inceptionv3.sh /${PROJECT_DIR}/run_extract_inceptionv3.sh
RUN chmod +x run_extract_inceptionv3.sh && \
    ./run_extract_inceptionv3.sh


FROM tensorflow/tensorflow:latest

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api_tf2_serving.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install gcc libev-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install -r requirements_api_tf2_serving.txt

COPY ./src/ /${PROJECT_DIR}/src/
COPY ./logging/ /${PROJECT_DIR}/logging/
COPY --from=builder /${PROJECT_DIR}/models/* ./models/

ENV RUN_FILE run_backend.sh
COPY ./scripts/${RUN_FILE} /${PROJECT_DIR}/${RUN_FILE}
RUN chmod +x ${RUN_FILE}
CMD ./run_backend.sh