FROM python:3.7-slim

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install gcc curl && \
    pip install -r requirements_api.txt

COPY ./app/ml/ /${PROJECT_DIR}/app/ml/
COPY ./jobs/ /${PROJECT_DIR}/jobs/
COPY ./middleware/ /${PROJECT_DIR}/middleware/
COPY ./configurations/ /${PROJECT_DIR}/configurations/
COPY ./app/constants.py /${PROJECT_DIR}/app/constants.py
COPY ./scripts/run_extract_resnet50.sh /${PROJECT_DIR}/run_extract_resnet50.sh

RUN chmod +x run_extract_resnet50.sh

CMD ./run_extract_resnet50.sh
