FROM python:3.7-slim as builder

ENV PROJECT_DIR /serving_patterns/
WORKDIR ${PROJECT_DIR}
ADD requirements/requirements_api.txt ${PROJECT_DIR}
RUN apt-get -y update && \
    apt-get -y install gcc && \
    pip install -r requirements_api.txt

COPY ./app/ ${PROJECT_DIR}app/
ENV RUN_FILE run_train_iris.sh
COPY ./scripts/${RUN_FILE} ${PROJECT_DIR}${RUN_FILE}
RUN chmod +x ${RUN_FILE} && \
    ./run_train_iris.sh


FROM python:3.7-slim

ENV PROJECT_DIR /serving_patterns/
WORKDIR ${PROJECT_DIR}
ADD requirements/requirements_api.txt ${PROJECT_DIR}
RUN apt-get -y update && \
    apt-get -y install gcc && \
    pip install -r requirements_api.txt

COPY ./app/ ${PROJECT_DIR}app/
COPY --from=builder ${PROJECT_DIR}models/* ./models/

ENV RUN_FILE run_backend.sh
COPY ./scripts/${RUN_FILE} ${PROJECT_DIR}${RUN_FILE}
RUN chmod +x ${RUN_FILE}
CMD ./run_backend.sh