FROM python:3.7-slim as builder

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc && \
    pip install  --no-cache-dir -r requirements_api.txt

COPY ./src/app/ml/ /${PROJECT_DIR}/src/app/ml/
COPY ./src/app/constants.py /${PROJECT_DIR}/src/app/constants.py
COPY ./src/configurations/ /${PROJECT_DIR}/src/configurations/

ENV RUN_FILE run_train_iris.sh
COPY ./scripts/${RUN_FILE} /${PROJECT_DIR}/${RUN_FILE}
RUN chmod +x ${RUN_FILE} && \
    ./run_train_iris.sh


FROM python:3.7-slim

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc && \
    pip install  --no-cache-dir -r requirements_api.txt

COPY ./src/ /${PROJECT_DIR}/src/
COPY ./logging/ /${PROJECT_DIR}/logging/
COPY --from=builder /${PROJECT_DIR}/models/* ./models/

ENV RUN_FILE run_backend.sh
COPY ./scripts/${RUN_FILE} /${PROJECT_DIR}/${RUN_FILE}
RUN chmod +x ${RUN_FILE}
CMD ./run_backend.sh