FROM python:3.7-slim as builder

ENV PROJECT_DIR /serving_patterns/
WORKDIR ${PROJECT_DIR}
ADD requirements/requirements_api_tf2.txt ${PROJECT_DIR}
RUN apt-get -y update && \
    apt-get -y install gcc curl && \
    pip install -r requirements_api_tf2.txt

COPY ./app/ ${PROJECT_DIR}app/
COPY ./scripts/run_extract_imagenet_inceptionv3.sh ${PROJECT_DIR}run_extract_imagenet_inceptionv3.sh
RUN chmod +x run_extract_imagenet_inceptionv3.sh
RUN ./run_extract_imagenet_inceptionv3.sh


FROM tensorflow/serving:latest

COPY --from=builder /serving_patterns/models/savedmodel/inceptionv3 /models/inceptionv3
ENV MODEL_NAME inceptionv3
