FROM tensorflow/tensorflow:latest as builder

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api_tf2.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install gcc curl && \
    pip install -r requirements_api_tf2.txt

COPY ./app/ml/ /${PROJECT_DIR}/app/ml/
COPY ./app/constants.py /${PROJECT_DIR}/app/constants.py
COPY ./configurations/ /${PROJECT_DIR}/configurations/
COPY ./scripts/run_extract_resnet50_tfs.sh /${PROJECT_DIR}/run_extract_resnet50_tfs.sh
RUN chmod +x run_extract_resnet50_tfs.sh && \
    ./run_extract_resnet50_tfs.sh


FROM tensorflow/tensorflow:latest

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api_tf2_serving.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install gcc && \
    pip install -r requirements_api_tf2_serving.txt

COPY ./app/ /${PROJECT_DIR}/app/
COPY ./jobs/ /${PROJECT_DIR}/jobs/
COPY ./middleware/ /${PROJECT_DIR}/middleware/
COPY ./configurations/ /${PROJECT_DIR}/configurations/
COPY ./logging/ /${PROJECT_DIR}/logging/
COPY --from=builder /${PROJECT_DIR}/models/* ./models/

ENV RUN_FILE run_api.sh
COPY ./scripts/${RUN_FILE} /${PROJECT_DIR}/${RUN_FILE}
RUN chmod +x ${RUN_FILE}
CMD ./run_api.sh
