FROM python:3.7-slim as builder

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc curl && \
    pip install  --no-cache-dir -r requirements_api.txt

COPY ./src/ /${PROJECT_DIR}/src/

ENV RUN_FILE run_train_iris.sh
COPY ./scripts/${RUN_FILE} /${PROJECT_DIR}/${RUN_FILE}
RUN chmod +x ${RUN_FILE}
CMD ./run_train_iris.sh