FROM python:3.7-slim

ENV PROJECT_DIR /serving_patterns/
WORKDIR ${PROJECT_DIR}
ADD requirements/requirements_api.txt ${PROJECT_DIR}
RUN apt-get -y update && \
    apt-get -y install gcc curl && \
    pip install -r requirements_api.txt

COPY ./app/ ${PROJECT_DIR}app/
COPY ./models/ ${PROJECT_DIR}models/
COPY ./scripts/get_imagenet_resnet50v2_onnx.sh ${PROJECT_DIR}get_imagenet_resnet50v2_onnx.sh
COPY ./scripts/run_extract_imagenet_resnet50.sh ${PROJECT_DIR}run_extract_imagenet_resnet50.sh
RUN chmod +x get_imagenet_resnet50v2_onnx.sh
RUN ./get_imagenet_resnet50v2_onnx.sh
RUN chmod +x run_extract_imagenet_resnet50.sh
CMD ./run_extract_imagenet_resnet50.sh
