FROM continuumio/miniconda:latest as builder

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_pytorch.txt /${PROJECT_DIR}/
ADD requirements/conda_pytorch.yaml /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc curl && \
    conda update -n base -c defaults conda && \
    conda env update -f conda_pytorch.yaml && \
    conda install pytorch torchvision cpuonly -c pytorch && \
    conda clean -y --all && \
    pip install  --no-cache-dir -r requirements_pytorch.txt

COPY ./src/app/ml/ /${PROJECT_DIR}/src/app/ml/
COPY ./src/app/constants.py /${PROJECT_DIR}/src/app/constants.py
COPY ./src/configurations/ /${PROJECT_DIR}/src/configurations/
COPY ./scripts/run_extract_resnet50_onnx.sh /${PROJECT_DIR}/run_extract_resnet50_onnx.sh

RUN chmod +x run_extract_resnet50_onnx.sh && \
    ./run_extract_resnet50_onnx.sh


FROM continuumio/miniconda:latest

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api.txt /${PROJECT_DIR}/
ADD requirements/conda_pytorch.yaml /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc curl && \
    conda update -n base -c defaults conda && \
    conda env update -f conda_pytorch.yaml && \
    conda install pytorch torchvision cpuonly -c pytorch && \
    conda clean -y --all && \
    pip install  --no-cache-dir -r requirements_api.txt

COPY ./src/ /${PROJECT_DIR}/src/
COPY ./logging/ /${PROJECT_DIR}/logging/
COPY --from=builder /${PROJECT_DIR}/models/* ./models/

ENV RUN_FILE run_backend.sh
COPY ./scripts/${RUN_FILE} /${PROJECT_DIR}/${RUN_FILE}
RUN chmod +x ${RUN_FILE}
CMD ./run_backend.sh