FROM python:3.7-slim

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_pytorch.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install gcc curl libev-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install -r requirements_pytorch.txt

COPY ./src/ /${PROJECT_DIR}/src/
COPY ./scripts/run_extract_resnet50_onnx.sh /${PROJECT_DIR}/run_extract_resnet50_onnx.sh

RUN chmod +x run_extract_resnet50_onnx.sh

CMD ./run_extract_resnet50_onnx.sh
