FROM python:3.7-slim

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_test.txt /${PROJECT_DIR}
RUN apt-get -y update && \
    apt-get -y install gcc libev-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install -r requirements_test.txt

COPY ./src/ /${PROJECT_DIR}/src/
COPY ./logging/ /${PROJECT_DIR}/logging/
COPY ./tests/ /${PROJECT_DIR}/tests/
CMD ['pytest', '-v', '-s', './tests/']
