FROM python:3.7-slim as builder

ENV PROJECT_DIR /serving_patterns/
WORKDIR ${PROJECT_DIR}
ADD requirements/requirements_api_tf2.txt ${PROJECT_DIR}
RUN apt-get -y update && \
    apt-get -y install gcc curl && \
    pip install -r requirements_api_tf2.txt

COPY ./app/ ${PROJECT_DIR}app/
COPY ./scripts/run_extract_imagenet_inceptionv3.sh ${PROJECT_DIR}run_extract_imagenet_inceptionv3.sh
RUN chmod +x run_extract_imagenet_inceptionv3.sh
RUN ./run_extract_imagenet_inceptionv3.sh


FROM python:3.7-slim

ENV PROJECT_DIR /serving_patterns/
WORKDIR ${PROJECT_DIR}
ADD requirements/requirements_api_tf2_serving.txt ${PROJECT_DIR}
RUN apt-get -y update && \
    apt-get -y install gcc && \
    pip install -r requirements_api_tf2_serving.txt

COPY ./app/ ${PROJECT_DIR}app/
COPY --from=builder ${PROJECT_DIR}models/* ./models/

ENV RUN_FILE run_api.sh
COPY ./scripts/${RUN_FILE} ${PROJECT_DIR}${RUN_FILE}
RUN chmod +x ${RUN_FILE}
CMD ./run_api.sh
