apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mobilenetv2-tfs-sidecar-tfs-sidecar
  labels:
    app: api-mobilenetv2-tfs-sidecar
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-mobilenetv2-tfs-sidecar
  replicas: 2
  template:
    metadata:
      labels:
        app: api-mobilenetv2-tfs-sidecar
      name: api-mobilenetv2-tfs-sidecar
    spec:
      containers:
        - name: api-mobilenetv2-tfs-sidecar
          image: shibui/ml-system-in-action:serving_patterns_api_mobilenetv2
          command: ["./run_api.sh"]
          env:
            - name: PLATFORM
              value: kubernetes
            - name: CACHE_HOST
              value: redis.serving-pattern.svc.cluster.local
            - name: MODEL_INTERFACE
              value: /serving_patterns/src/app/ml/mobilenetv2/model/mobilenetv2.yaml
            - name: RUNNER
              value: GUNICORN
            - name: WORKERS
              value: "8"
            - name: BACKLOG
              value: "32"
            - name: LIMIT_MAX_REQUESTS
              value: "128"
            - name: MAX_REQUESTS_JITTER
              value: "128"
            - name: APP_NAME
              value: "src.app.apps.app_image:app"
            - name: PORT
              value: "8897"
            - name: PROFILE
              value: "0"
            - name: TFS_GRPC
              value: localhost:8512
            - name: QUEUE_NAME
              value: mobilenetv2_api_queue
          ports:
            - containerPort: 8897
          livenessProbe:
            httpGet:
              port: 8897
              path: /health
            failureThreshold: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8897
              path: /health
            failureThreshold: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: "8000Mi"
            requests:
              cpu: "2"
              memory: "8000Mi"
        - name: tfs-mobilenetv2
          image: shibui/ml-system-in-action:serving_patterns_tfs_mobilenetv2
          command: ["/usr/bin/tf_serving_entrypoint.sh"]
          env:
            - name: PORT
              value: "8512"
            - name: REST_API_PORT
              value: "8513"
            - name: MODEL_NAME
              value: mobilenetv2
            - name: MODEL_BASE_PATH
              value: /serving_patterns/src/app/ml/mobilenetv2/model/savedmodel/mobilenetv2
          resources:
            limits:
              cpu: "4"
              memory: "4000Mi"
            requests:
              cpu: "4"
              memory: "4000Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: api-mobilenetv2-tfs-sidecar
  labels:
    app: api-mobilenetv2-tfs-sidecar
  namespace: serving-pattern
spec:
  ports:
    - port: 8897
      protocol: TCP
  selector:
    app: api-mobilenetv2-tfs-sidecar
