apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-resnet50-flask-onnx
  labels:
    app: api-resnet50-flask-onnx
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-resnet50-flask-onnx
  replicas: 4
  template:
    metadata:
      labels:
        app: api-resnet50-flask-onnx
      name: api-resnet50-flask-onnx
    spec:
      containers:
        - name: api-resnet50-flask-onnx
          image: shibui/ml-system-in-action:serving_patterns_api_resnet50_flask_onnx
          command: ["./run_api.sh"]
          env:
            - name: PLATFORM
              value: kubernetes
            - name: CACHE_HOST
              value: redis.serving-pattern.svc.cluster.local
            - name: MODEL_INTERFACE
              value: /serving_patterns/src/app/ml/resnet50_onnx/model/resnet50_onnx.yaml
            - name: RUNNER
              value: FLASK
            - name: WORKERS
              value: "24"
            - name: BACKLOG
              value: "64"
            - name: LIMIT_MAX_REQUESTS
              value: "400"
            - name: MAX_REQUESTS_JITTER
              value: "200"
            - name: GRACEFUL_TIMEOUT
              value: "10"
            - name: APP_NAME
              value: "src.app.apps.app_flask:app"
            - name: PORT
              value: "8895"
            - name: PROFILE
              value: "1"
            - name: QUEUE_NAME
              value: resnet50_api_queue
          ports:
            - containerPort: 8895
          livenessProbe:
            httpGet:
              port: 8895
              path: /health
            failureThreshold: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8895
              path: /health
            failureThreshold: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: "8000Mi"
            requests:
              cpu: "2"
              memory: "8000Mi"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-resnet50-flask-onnx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-resnet50-flask-onnx
  minReplicas: 1
  maxReplicas: 16
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: api-resnet50-flask-onnx
  labels:
    app: api-resnet50-flask-onnx
  namespace: serving-pattern
spec:
  ports:
    - port: 8895
      protocol: TCP
  selector:
    app: api-resnet50-flask-onnx
