apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-resnet50-onnx-server
  labels:
    app: api-resnet50-onnx-server
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-resnet50-onnx-server
  replicas: 2
  template:
    metadata:
      labels:
        app: api-resnet50-onnx-server
      name: api-resnet50-onnx-server
    spec:
      containers:
        - name: api-resnet50-onnx-server
          image: shibui/ml-system-in-action:serving_patterns_api_resnet50_onnx_server
          command: ["./run_api.sh"]
          env:
            - name: PLATFORM
              value: kubernetes
            - name: CACHE_HOST
              value: redis.serving-pattern.svc.cluster.local
            - name: MODEL_INTERFACE
              value: /serving_patterns/src/app/ml/resnet50_onnx_server/model/resnet50_onnx_server.yaml
            - name: RUNNER
              value: GUNICORN
            - name: WORKERS
              value: "24"
            - name: BACKLOG
              value: "64"
            - name: LIMIT_MAX_REQUESTS
              value: "400"
            - name: MAX_REQUESTS_JITTER
              value: "200"
            - name: GRACEFUL_TIMEOUT
              value: "10"
            - name: APP_NAME
              value: "src.app.apps.app_image:app"
            - name: ONNX_RUNTIME_SERVER_HTTP
              value: server-resnet50-onnx-server.serving-pattern.svc.cluster.local:8001
            - name: MODEL_NAME
              value: default
            - name: VERSION
              value: "1"
            - name: PORT
              value: "8896"
            - name: PROFILE
              value: "1"
            - name: QUEUE_NAME
              value: resnet50_api_server_queue
          ports:
            - containerPort: 8896
          livenessProbe:
            httpGet:
              port: 8896
              path: /health
            failureThreshold: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8896
              path: /health
            failureThreshold: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: "8000Mi"
            requests:
              cpu: "2"
              memory: "8000Mi"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-resnet50-onnx-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-resnet50-onnx-server
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: api-resnet50-onnx-server
  labels:
    app: api-resnet50-onnx-server
  namespace: serving-pattern
spec:
  ports:
    - port: 8896
      protocol: TCP
  selector:
    app: api-resnet50-onnx-server
