apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mobilenetv2
  labels:
    app: backend-mobilenetv2
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: backend-mobilenetv2
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-mobilenetv2
      name: backend-mobilenetv2
    spec:
      containers:
        - name: backend-mobilenetv2
          image: shibui/ml-system-in-action:serving_patterns_backend_mobilenetv2
          command: ["./run_backend.sh"]
          env:
            - name: PLATFORM
              value: kubernetes
            - name: CACHE_HOST
              value: redis.serving-pattern.svc.cluster.local
            - name: MODEL_INTERFACE
              value: /serving_patterns/src/app/ml/mobilenetv2/model/mobilenetv2.yaml
            - name: NUM_PROCS
              value: "4"
            - name: BATCH_CODE
              value: "src.app.backend.prediction_batch"
            - name: PREDICTOR
              value: "src.app.api._predict_image"
            - name: PROFILE
              value: "0"
            - name: TFS_GRPC
              value: tfs-mobilenetv2.serving-pattern.svc.cluster.local:8512
            - name: QUEUE_NAME
              value: mobilenetv2_api_queue
          resources:
            limits:
              cpu: "1"
              memory: "4000Mi"
            requests:
              cpu: "1"
              memory: "4000Mi"
