apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-locust
  labels:
    app: load-test-locust
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: load-test-locust
  replicas: 1
  template:
    metadata:
      labels:
        app: load-test-locust
      name: load-test-locust
    spec:
      containers:
        - name: load-test-locust
          image: shibui/ml-system-in-action:load_test_locust
          command: ["locust"]
          args: ["-f", "$(TARGET_FILE)"]
          env:
            - name: PLATFORM
              value: kubernetes
            - name: TARGET_FILE
              value: image_classification_all.py
            - name: POST_PREDICT_LABEL_RATIO
              value: "1"
          ports:
            - containerPort: 8089
          resources:
            limits:
              cpu: "2"
              memory: "2000Mi"
            requests:
              cpu: "2"
              memory: "2000Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: load-test-locust
  labels:
    app: load-test-locust
  namespace: serving-pattern
spec:
  ports:
    - port: 8089
      protocol: TCP
  selector:
    app: load-test-locust
