apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-resnet50-onnx-server
  labels:
    app: server-resnet50-onnx-server
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: server-resnet50-onnx-server
  replicas: 2
  template:
    metadata:
      labels:
        app: server-resnet50-onnx-server
      name: server-resnet50-onnx-server
    spec:
      containers:
        - name: server-resnet50-onnx-server
          image: shibui/ml-system-in-action:serving_patterns_server_resnet50_onnx_server
          command: ["./onnx_runtime_server_entrypoint.sh"]
          env:
            - name: HTTP_PORT
              value: "8001"
            - name: GRPC_PORT
              value: "50051"
            - name: LOGLEVEL
              value: debug
            - name: NUM_HTTP_THREADS
              value: "2"
            - name: MODEL_PATH
              value: /serving_patterns/src/app/ml/resnet50_onnx_server/model/resnet50v2.onnx
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              port: 8001
              path: /
            failureThreshold: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8001
              path: /
            failureThreshold: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: "4000Mi"
            requests:
              cpu: "2"
              memory: "4000Mi"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: server-resnet50-onnx-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-resnet50-onnx-server
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: server-resnet50-onnx-server
  labels:
    app: server-resnet50-onnx-server
  namespace: serving-pattern
spec:
  ports:
    - port: 8001
      protocol: TCP
  selector:
    app: server-resnet50-onnx-server
