version: "3"

services:
  prep_pred_api_resnet50:
    container_name: serving_patterns_prep_pred_api_resnet50
    build:
      context: ..
      dockerfile: src/app/ml/resnet50_tfs/Dockerfile_api_resnet50_tfs
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=/serving_patterns/src/app/ml/resnet50_tfs/model/resnet50_tfs.yaml
      - RUNNER=GUNICORN
      - WORKERS=4
      - BACKLOG=64
      - LIMIT_MAX_REQUESTS=1024
      - MAX_REQUESTS_JITTER=128
      - APP_NAME=src.app.apps.app_image:app
      - PORT=8894
      - TFS_GRPC=prep_pred_tfs_resnet50:8514
      - PROFILE=0
      - QUEUE_NAME=tfs_queue
    ports:
      - "8894:8894"
    command: ./run_api.sh
    depends_on:
      - redis
      - prep_pred_tfs_resnet50
      - prep_pred_backend_resnet50

  prep_pred_tfs_resnet50:
    container_name: serving_patterns_prep_pred_tfs_resnet50
    build:
      context: ..
      dockerfile: src/app/ml/resnet50_tfs/Dockerfile_tfserving_resnet50
    environment:
      - PORT=8514
      - REST_API_PORT=8515
      - MODEL_NAME=resnet_v2_50
      - MODEL_BASE_PATH=/serving_patterns/src/app/ml/resnet50_tfs/model/savedmodel/resnet_v2_50
    ports:
      - "8514:8514"
      - "8515:8515"
    entrypoint: ["/usr/bin/tf_serving_entrypoint.sh"]

  prep_pred_backend_resnet50:
    container_name: serving_patterns_prep_pred_backend_resnet50
    build:
      context: ..
      dockerfile: src/app/ml/resnet50_tfs/Dockerfile_backend_resnet50_tfs
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=/serving_patterns/src/app/ml/resnet50_tfs/model/resnet50_tfs.yaml
      - NUM_PROCS=4
      - BATCH_CODE=src.app.backend.prediction_batch
      - TFS_GRPC=prep_pred_tfs_resnet50:8514
      - PROFILE=0
      - PREDICTOR=src.app.api._predict_image
      - QUEUE_NAME=tfs_queue
    command: ./run_backend.sh
    depends_on:
      - redis

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
