version: "3"

services:
  web_single_iris:
    container_name: serving_patterns_web_single_iris
    build:
      context: ..
      dockerfile: src/app/ml/iris/Dockerfile_api_iris
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=/serving_patterns/src/app/ml/iris/model/iris_svc_sklearn.yaml
      - RUNNER=GUNICORN
      - WORKERS=4
      - BACKLOG=16
      - LIMIT_MAX_REQUESTS=128
      - MAX_REQUESTS_JITTER=32
      - APP_NAME=src.app.apps.app_web_single:app
      - PORT=8888
      - PROFILE=0
      - QUEUE_NAME=api_queue
    ports:
      - "8888:8888"
    command: ./run_api.sh
    depends_on:
      - redis

  synchronous_iris:
    container_name: serving_patterns_synchronous_iris
    build:
      context: ..
      dockerfile: src/app/ml/iris/Dockerfile_api_iris
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=/serving_patterns/src/app/ml/iris/model/iris_svc_onnx_runtime.yaml
      - RUNNER=GUNICORN
      - WORKERS=4
      - BACKLOG=16
      - LIMIT_MAX_REQUESTS=128
      - MAX_REQUESTS_JITTER=32
      - APP_NAME=src.app.apps.app_synchronous:app
      - PORT=8889
      - PROFILE=0
      - QUEUE_NAME=api_queue
    ports:
      - "8889:8889"
    command: ./run_api.sh
    depends_on:
      - redis

  asynchronous_iris:
    container_name: serving_patterns_asynchronous_iris
    build:
      context: ..
      dockerfile: src/app/ml/iris/Dockerfile_api_iris
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=/serving_patterns/src/app/ml/iris/model/iris_tree_onnx_runtime.yaml
      - RUNNER=GUNICORN
      - WORKERS=4
      - BACKLOG=16
      - LIMIT_MAX_REQUESTS=128
      - MAX_REQUESTS_JITTER=32
      - APP_NAME=src.app.apps.app_asynchronous:app
      - PORT=8890
      - PROFILE=0
      - QUEUE_NAME=api_queue
    ports:
      - "8890:8890"
    command: ./run_api.sh
    depends_on:
      - api_backend_iris
      - redis

  api_backend_iris:
    container_name: serving_patterns_backend_iris
    build:
      context: ..
      dockerfile: src/app/ml/iris/Dockerfile_backend_iris
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=/serving_patterns/src/app/ml/iris/model/iris_tree_onnx_runtime.yaml
      - NUM_PROCS=4
      - BATCH_CODE=src.app.backend.prediction_batch
      - PROFILE=0
      - QUEUE_NAME=api_queue
    command: ./run_backend.sh
    depends_on:
      - redis

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
