version: "3"

services:
  prep_pred_api_mobilenetv2_plant:
    container_name: serving_patterns_prep_pred_api_mobilenetv2_plant
    build:
      context: ..
      dockerfile: src/app/ml/mobilenetv2_plant/Dockerfile_api_mobilenetv2_plant
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=/serving_patterns/src/app/ml/mobilenetv2_plant/model/mobilenetv2_plant.yaml
      - RUNNER=GUNICORN
      - WORKERS=4
      - BACKLOG=64
      - LIMIT_MAX_REQUESTS=1024
      - MAX_REQUESTS_JITTER=128
      - APP_NAME=src.app.apps.app_image:app
      - PORT=8893
      - TFS_GRPC=prep_pred_tfs_mobilenetv2_plant:8514
      - PROFILE=0
      - QUEUE_NAME=tfs_queue
    ports:
      - "8893:8893"
    command: ./run_api.sh
    depends_on:
      - redis
      - prep_pred_tfs_mobilenetv2_plant
      - prep_pred_backend_mobilenetv2_plant

  prep_pred_tfs_mobilenetv2_plant:
    container_name: serving_patterns_prep_pred_tfs_mobilenetv2_plant
    build:
      context: ..
      dockerfile: src/app/ml/mobilenetv2_plant/Dockerfile_tfserving_mobilenetv2_plant
    environment:
      - PORT=8514
      - REST_API_PORT=8515
      - MODEL_NAME=mobilenetv2_plant
      - MODEL_BASE_PATH=/serving_patterns/src/app/ml/mobilenetv2_plant/model/savedmodel/mobilenetv2_plant
    ports:
      - "8514:8514"
      - "8515:8515"
    entrypoint: ["/usr/bin/tf_serving_entrypoint.sh"]

  prep_pred_backend_mobilenetv2_plant:
    container_name: serving_patterns_prep_pred_backend_mobilenetv2_plant
    build:
      context: ..
      dockerfile: src/app/ml/mobilenetv2_plant/Dockerfile_backend_mobilenetv2_plant
    environment:
      - PLATFORM=docker_compose
      - MODEL_INTERFACE=/serving_patterns/src/app/ml/mobilenetv2_plant/model/mobilenetv2_plant.yaml
      - NUM_PROCS=4
      - BATCH_CODE=src.app.backend.prediction_batch
      - TFS_GRPC=prep_pred_tfs_mobilenetv2_plant:8514
      - PROFILE=0
      - PREDICTOR=src.app.api._predict_image
      - QUEUE_NAME=tfs_queue
    command: ./run_backend.sh
    depends_on:
      - redis

  redis:
    container_name: serving_patterns_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
